def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('home', '/')
    config.add_route('about', '/about')
    config.add_route('test2', '/test2')
    config.add_route('test3', '/test3')
    config.add_route('artists1', '/Till_Lindemann')
    config.add_route('artists2', '/Christian_Lorenz')
    config.add_route('artists3', '/Christoph_Doom_Schneider')
    config.add_route('artists4', '/Oliver_Riedel')
    config.add_route('artists5', '/Paul_Landers')
    config.add_route('artists6', '/Richard_Kruspe-Bernstein')
    config.add_route('Herzeleid', '/Herzeleid')
    config.add_route('Sehnsucht', '/Sehnsucht')

